---
title: "Lab 00 - Hello IDS!"
author: "Yunis"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Ozcan", "Rino", "Calum", 
           "Jerry", "Grace", "Yunis"),
  github_username = c("OzjanMasiyev", "RinoDiRollo976", "Calumwatson28", 
                      "jerry00801-spec", "yueyin710-ai", "Yuniss07"), 
  colour = c("blue", "blue", "red", 
             "blue", "green", "green"),
  hobby = c("Piano", "football", "hiking", 
            "swimming", "music", "football"),
  favourite_number = c(7, 3, 7, 7, 7, 7)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```

Half of the team members' favorite color is blue, while 2 of the members like green. The majority of members like the number '7'. 

